### ISSUE TITLE
Unable to parse logs with logstash after release 1.1.4

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/windows-syslog-release#13]
When updating our deployment with any release that includes the new syslog components, our logstash pipeline fails to process any logs from Windows 2019 cells.  It appears to because the syslog entries emitted are not terminated by a newline character, which is required for logstash to parse them.  Here is an example of the data received via tcpdump (specifically **tcpdump -nnvvXS tcp port 5514**):

        0x01f0:  3135 5431 373a 3330 3a34 312e 3335 3031  15T17:30:41.3501
        0x0200:  3731 3339 325a 222c 2273 6573 7369 6f6e  71392Z","session
        0x0210:  223a 2232 3337 227d 7d34 3936 203c 3134  ":"237"}}496.<14
        0x0220:  3e31 2032 3032 322d 3037 2d31 3554 3137  >1.2022-07-15T17
        0x0230:  3a33 303a 3432 2e33 3034 3531 395a 2031  :30:42.304519Z.1

As you can see the next syslog message begins immediately with no termination, and logstash parses all of them as one big message until it reaches it's max length limit.  I've seen other references to this issue such as https://github.com/winstonjs/winston-syslog/issues/47.

Rolling back the release to 1.1.4 fixes the problem, and I've confirmed that all messages are terminated with a "\n" when using that version.  With either 1.1.4 or 1.1.7, logs from the Linux VMs are correctly formatted with a "\n" at the end of every message.  I also confirmed that the recent change in 1.1.7 to strip a "\r" from the end of the line didn't make any difference.

Can we modify the logic to make sure that a "\n" is present at the end of every message, if it's not there already?

**Comment by Benjamintf1** [comment]
Sorry for not getting back to yall earlier. I'd recomend reaching out to #logging-and-metrics in the cloudfoundry slack if you want our attention. 

I can't entirely remember the exact mindset that led us to strip \r from messages, although I recall having a lot of difficulty with encoding and message compatibility when implementing the event feature and trying to fix this bug https://github.com/cloudfoundry/windows-syslog-release/issues/6. 

Making sure syslog messages are valid is a good idea and I'd be interested in looking at prs to fix it.

**Comment by Benjamintf1** [comment]
I think I *possibly* see the issue. I havn't fully vetted this landscape, but it might be from the switch from transparent framing to octect count based framing which seemed to happen in a blackbox change. Log-stash should be able to support both.

**Comment by Benjamintf1** [comment]
I believe tailer removes the \n, so we removed \r from logs so they would not end with a \r but not a \n on windows. It resulted in some weird outcomes. It might be worth changing blackbox to re-add a \n, but also continue to use octect based framing, I *think* that might support both, but my understnading is we changed blackbox to octect based framing because rsyslog accepts both, but I *think* in terms of egress, rsyslog uses octect counting by default.

**Comment by amhuber** [comment]
I'm assuming there are no updates on this?

**Comment by amhuber** [comment]
I tried the latest release again just to see if there was any change and it is now working correctly.

**Comment by amhuber** [comment]
Oops, false alarm.  I forgot that it was the system logs that don't show up, not the app logs.  I'm still not getting any system logs from Windows via syslog due to this issue, re-opening.

**Comment by Benjamintf1** [comment]
Do you have a good idea if my description describes the issue well? Like, if you change to the other framing scheme does it work?(not that it's ideal for your usecase, but want to get an idea if we're on the right path here).

**Comment by Benjamintf1** [comment]
Specifically, if you change your log-stash to parse octect based framing, does it work? 

I think we switched to octect based framing because we were having trouble with the character encoding with windows?

**Comment by amhuber** [comment]
We're just using https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry to parse the logs so I'll have to check if that supports changing anything in logstash related to that.  I don't see anything in the spec at first glance, but since logstash is parsing logs from both Windows and Linux systems I'd be worried that changing anything would cause an issue with our Linux logs, which are still parsing just fine with the current syslog-release version.

I suspect we need blackbox on Windows to include a "\n" so it works consistently across both platforms, but I'll reply shortly if I find anything in the logsearch release that is configurable.

**Comment by amhuber** [comment]
From what I can see, the logsearch release is just using a TCP input plugin:

https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/ingestor_syslog/templates/config/input_and_output.conf.erb#L3-L10

The TCP input describes that each log entry has to be a specific line, meaning separated by a newline (\n) character:

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html

At the moment I'm not seeing any way we could configure the release to support log entries without a newline.

**Comment by ctlong** [comment]
I don't think we intend to add `\n` given that we prefer octet-framing. Ideally the community nozzle would implement this.

Also, I think Logsearch may have gone away given that logsearch.io is no longer registered? If it's been absorbed into the base ELK stack, then syslog input should be accepted natively.
